    #--- .NET Core Helpers ---#
alias dnr='dotnet run'
alias dnrp='dotnet run --launch-profile'
alias dnrpl='dotnet run --launch-profile "Local"'
alias dnwr='dotnet watch run'
alias dnwrp='dotnet watch run --launch-profile'
alias dnwrpl='dotnet watch run --launch-profile "Local"'
alias dnna='dotnet new webapi -o'
alias dnnc='dotnet new classlib -o'
alias dnnu='dotnet new nunit -o'
alias dna='dotnet add'
alias dnap='dotnet add package'
alias dnrm='dotnet remove'
alias dnrp='dotnet remove package'