alias cls="clear"
alias ..="cd .."
alias ....="cd ../.."

alias env='printenv'
alias look="find . -name"
alias search="grep --color -rnw ./ -e "
alias xclip="xclip -selection c"

alias ports="lsof -PiTCP -sTCP:LISTEN"

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias mkdir='mkdir -p'
alias h='history'
alias hs='history -a | grep'
alias j='jobs -l'
alias which='type -a'

alias path='echo -e ${PATH//:/\\n}'
alias libpath='echo -e ${LD_LIBRARY_PATH//:/\\n}'

alias du='du -kh'
alias df='df -kTh'

    #--- Directory Helpers ---#
alias lx='ls -lXB' # Sort by extension
alias lk='ls -lSr' # Sort by size, biggest last
alias lt='ls -ltr' # Sort by date, most recent last
alias lc='ls -ltcr' # Sort by/show change time,most recent last
alias lu='ls -ltur' # Sort by/show access time,most recent last
alias ll="ls -lv --group-directories-first" # 'll': directories first, with alphanumeric sorting
alias lm='ll |more' # Pipe through 'more'
alias la='ll -A' # Show hidden files
alias lr='ll -R' # Recursive ls

    #--- Git Helpers ---#
alias g='git'
alias ga='git add'
alias gaa='git add .'
alias gapa='git add --patch'
alias gau='git add --update'
alias gav='git add --verbose'
alias gap='git apply'
alias gbl='git branch -a'
alias gc='git commit -v'
alias gc!='git commit -v --amend'
alias gcn!='git commit -v --no-edit --amend'
alias gca='git commit -v -a'
alias gca!='git commit -v -a --amend'
alias gcan!='git commit -v -a --no-edit --amend'
alias gcans!='git commit -v -a -s --no-edit --amend'
alias gcam='git commit -a -m'
alias gcb='git checkout -b'
alias gcf='git config --list'
alias gcl='git clone --recurse-submodules'
alias gclean='git clean -id'
alias gpristine='git reset --hard && git clean -dffx'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcom='git checkout master'
alias gcod='git checkout develop'
alias gcm='git commit -m'
alias gcp='git cherry-pick'
alias gcpa='git cherry-pick --abort'
alias gcpc='git cherry-pick --continue'
alias gcs='git commit -S'
alias gcsm='git commit -s -m'
alias gd='git diff'
alias gdct='git describe --tags $(git rev-list --tags --max-count=1)'
alias gds='git diff --staged'
alias gdt='git diff-tree --no-commit-id --name-only -r'
alias gf='git fetch'
alias gfo='git fetch origin'
alias gfg='git ls-files | grep'
alias gl='git pull'
alias glg='git log --stat'
alias glgp='git log --stat -p'
alias glgg='git log --graph'
alias glgga='git log --graph --decorate --all'
alias glgm='git log --graph --max-count=10'
alias glo='git pull origin'
alias glod='git pull origin develop'
alias glodr='git pull origin develop --rebase'
alias glol="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'"
alias glola="git log --graph --pretty='%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --all"
alias glog='git log --oneline --decorate --graph'
alias gloga='git log --oneline --decorate --graph --all'
alias glom='git pull origin main'
alias glomr='git pull origin main --rebase'
alias glp="printGitLogPrettily"
alias gp='git push'
alias gpd='git push --dry-run'
alias gpf='git push --force-with-lease'
alias gpf!='git push --force'
alias gpo='git push origin'
alias gpoa='git push origin --all'
alias gpoat='git push origin --all && git push origin --tags'
alias gpod='git push origin develop'
alias gpodl='git push origin --delete'
alias gpom='git push origin main'
alias gpot='git push origin --tags'
alias grm='git rm --cached'
alias gs="git status"
alias gsb='git status -sb'
alias gsh='git show'
alias gsps='git show --pretty=short --show-signature'
alias gsr='git svn rebase'
alias gss='git status -s'
alias gst='git stash'
alias gstc='git stash clear'
alias gstp='git stash pop'
alias gsw='git switch'
alias gswd='git switch develop'
alias gswm='git switch main'
alias gt='git tag'
alias gta='git tag -a'
alias gtd='git tag -d'

    #--- kubectl Helpers ---#
alias kubectl='kubecolor'
alias k='kubectl'
alias ka='kubectl apply'
alias kaf='kubectl apply -f'
alias kak='kubectl apply -k'
alias kc='kubectl create'
alias kcd='kubectl create deployment'
alias kcn='kubectl create namespace'
alias kcp='kubectl create pod'
alias kcr='kubectl create replicaset'
alias kcs='kubectl create service'
alias kcf='kubectl config'
alias kcfc='kubectl config current-context'
alias kcfg='kubectl config get-contexts' 
alias kcfs='kubectl config set-context'
alias kcfsc='kubectl config set-context --current'
alias kcfu='kubectl config use-context'
alias kcfum='kubectl config use-context management-primary'
alias kcfup='kubectl config use-context production-primary'
alias kd='kubectl describe'
alias kdd='kubectl describe deployment'
alias kdds='kubectl describe deployments'
alias kdn='kubectl describe namespace'
alias kdns='kubectl describe namespaces'
alias kdp='kubectl describe pod'
alias kdps='kubectl describe pods'
alias kdr='kubectl describe replicaset'
alias kdrs='kubectl describe replicasets'
alias kds='kubectl describe service'
alias kdss='kubectl describe services'
alias kdl='kubectl delete'
alias kdld='kubectl delete deployment'
alias kdln='kubectl delete namespace'
alias kdlp='kubectl delete pod'
alias kdlr='kubectl delete replicaset'
alias kdls='kubectl delete service'
alias ke='kubectl edit'
alias ked='kubectl edit deployment'
alias ken='kubectl edit namespace'
alias kep='kubectl edit pod'
alias ker='kubectl edit replicaset'
alias kes='kubectl edit service'
alias kex='kubectl exec'
alias kexit='kubectl exec -it'
alias kg='kubectl get'
alias kgd='kubectl get deployment'
alias kgds='kubectl get deployments'
alias kgdsa='kubectl get deployments --all-namespaces'
alias kgdsc='kubectl get deployments --no-headers | wc -l'
alias kgdss='kubectl get deployments --selector'
alias kgn='kubectl get namespace'
alias kgns='kubectl get namespaces'
alias kgnsa='kubectl get namespaces --all-namespaces'
alias kgnss='kubectl get namespaces --selector'
alias kgp='kubectl get pod'
alias kgps='kubectl get pods -o wide'
alias kgpsa='kubectl get pods -o wide --all-namespaces'
alias kgpsc='kubectl get pods --no-headers | wc -l'
alias kgpss='kubectl get pods --selector'
alias kgr='kubectl get replicaset'
alias kgrs='kubectl get replicasets'
alias kgrsa='kubectl get replicasets --all-namespaces'
alias kgrsc='kubectl get replicasets --no-headers | wc -l'
alias kgrss='kubectl get replicasets --selector'
alias kgs='kubectl get service'
alias kgss='kubectl get services'
alias kgssa='kubectl get services --all-namespaces'
alias kgssc='kubectl get services --no-headers | wc -l'
alias kgsss='kubectl get services --selector'
alias kl='kubectl logs'
alias klf='kubectl logs -f'
alias kpf='kubectl port-forward'
alias kr='kubectl run'
alias ktop='kubectl top'
alias kttn='kubectl taint nodes'

    #--- Directory Helpers ---#
alias tree='colorls --tree'
alias treed='colorls --tree -d'
alias treed2='colorls --tree=2 -d'
alias treed3='colorls --tree=3 -d'
alias treef='colorls --tree -f'
alias treef2='colorls --tree=2 -f'
alias treef3='colorls --tree=3 -f'
alias ls='colorls -lA --sd'