#--- Global Settings ---#
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(custom_os_icon context dir dir_writable vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(command_execution_time status time)
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=$'\ue0b0' # 
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=$'\ue0b2' # 
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
#--- OS Segment Settings ---#
POWERLEVEL9K_CUSTOM_OS_ICON_FOREGROUND='124'
POWERLEVEL9K_CUSTOM_OS_ICON_BACKGROUND='255'
POWERLEVEL9K_CUSTOM_OS_ICON='echo $MY_OS_ICON'
#--- Context Segment Settings ---#
POWERLEVEL9K_CONTEXT_TEMPLATE='%n'
POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND='015'
POWERLEVEL9K_CONTEXT_DEFAULT_BACKGROUND='124'
POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND='015'
POWERLEVEL9K_CONTEXT_REMOTE_BACKGROUND='054'
POWERLEVEL9K_CONTEXT_REMOTE_SUDO_FOREGROUND='015'
POWERLEVEL9K_CONTEXT_REMOTE_SUDO_BACKGROUND='054'
POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND='124'
POWERLEVEL9K_CONTEXT_SUDO_BACKGROUND='124'
#--- Directory Segment Settings ---#
POWERLEVEL9K_DIR_BACKGROUND='032'
POWERLEVEL9K_DIR_FOREGROUND='black'
POWERLEVEL9K_DIR_HOME_FOREGROUND='015'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='015'
POWERLEVEL9K_ETC_ICON=$'\uf423' # 
POWERLEVEL9K_FOLDER_ICON=$'\uf07b' # 
POWERLEVEL9K_HOME_ICON=$'\uf015' # 
POWERLEVEL9K_HOME_SUB_ICON=$'\uf07c' # 
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
#--- Read-Only Segment Settings ---#
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND='124'
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND='015'
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_ICON=$'\uf023' # 
POWERLEVEL9K_DIR_WRITABLE_ICON=$'\uf023' # 
