#--- Resource Segment Settings Definitions ---#
POWERLEVEL9K_VPN_IP_BACKGROUND='250'
POWERLEVEL9K_CUSTOM_WIFI_SIGNAL_BACKGROUND="245"
POWERLEVEL9K_CUSTOM_WIFI_SIGNAL_FOREGROUND="black"
POWERLEVEL9K_CUSTOM_AVG_LOAD_BACKGROUND="240"
POWERLEVEL9K_CUSTOM_AVG_LOAD_FOREGROUND="015"
POWERLEVEL9K_CUSTOM_MEMORY_UTIL_BACKGROUND="236"
POWERLEVEL9K_CUSTOM_MEMORY_UTIL_FOREGROUND="015"
POWERLEVEL9K_BATTERY_FOREGROUND='015'
POWERLEVEL9K_BATTERY_CHARGING_BACKGROUND='232'
POWERLEVEL9K_BATTERY_DISCONNECTED_BACKGROUND='232'
POWERLEVEL9K_BATTERY_LOW_BACKGROUND='232'
POWERLEVEL9K_BATTERY_STAGES=("%{%F{red}%}\uf244%{%f%} " "%{%F{yellow}%}\uf243%{%f%} " "%{%F{yellow}%}\uf242%{%f%} " "%{%F{green}%}\uf241%{%f%} " "%{%F{green}%}\uf240%{%f%} ") #         
POWERLEVEL9K_BATTERY_LOW_THRESHOLD='10'
