#--- Status Segment Settings ---#
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND="250"
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND="008"
POWERLEVEL9K_STATUS_FOREGROUND='016'
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='244'
POWERLEVEL9K_STATUS_OK_BACKGROUND='244'
POWERLEVEL9K_STATUS_VERBOSE=true
POWERLEVEL9K_TIME_FOREGROUND='015'
POWERLEVEL9K_TIME_BACKGROUND='236'
POWERLEVEL9K_TIME_FORMAT="%D{%H:%M \uf017  %m/%d/%y \uf073 }" #  
POWERLEVEL9K_TIME_ICON=''
